site_name: MunchMail
theme: yeti
dev_addr: '127.0.0.1:8092'
pages:
  - [index.md, "Guide du développeur"]
  - [api/intro.md, "L'API", "Introduction"]
  - [api/auth.md, "L'API", "Authentification"]
  - [api/tutoriel.md, "L'API", "Tutoriel : un envoi de A à Z"]
  - [editeur/exemple.md, "L'API", "Campagnes"]
  - [api/campagnes.md, "L'API", "Campagnes"]
  - [api/domaines.md, "L'API", "Domaines"]
  - [api/tracking.md, "L'API", "Suivi des actions côté destinataire"]
  - [api/stats.md, "L'API", "Statistiques"]
  - [editeur/integration.md, "Éditeur", 'Intégration']
  - [editeur/creation-template.md, "Éditeur", 'Création de template']
  - [exemples/php.md, "Exemples de code", "PHP"]
  - [faq.md, FAQ]
  - [annexes.md, Annexes]