site_name: MunchMail
theme: yeti
dev_addr: '127.0.0.1:8092'
pages:
  - [index.md, "Guide du développeur"]
  - [api/intro.md, "L'API", "Introduction"]
  - [api/auth.md, "L'API", "Authentification"]
  - [api/campagnes.md, "L'API", "Campagnes"]
  - [api/domaines.md, "L'API", "Domaines"]
  - [api/tutoriel.md, "L'API", "Tutoriel : un envoi de A à Z"]
  - [exemples/php.md, "Exemples de code", "PHP"]
  - [faq.md, FAQ]
  - [annexes.md, Annexes]
