site_name: MunchMail
theme: yeti
dev_addr: '127.0.0.1:8092'
pages:
  - [index.md, "Guide du développeur"]
  - [api/intro.md, "L'API", "Introduction"]
  - [api/auth.md, "L'API", "Authentification & utilisateurs"]
  - [api/tutoriel.md, "L'API", "Tutoriel : un envoi de A à Z"]
  - [api/categories.md, "L'API", "Catégories"]
  - [api/domaines.md, "L'API", "Domaines"]
  - [api/tracking.md, "L'API", "Suivi des actions côté destinataire"]
  - [api/mailmerge.md, "L'API", "Publipostage"]
  - [api/stats.md, "L'API", "Statistiques"]
  - [api/export.md, "L'API", "Exports & formats"]
  - [api/users.md, "L'API", "Utilisateurs & permissions"]
  - [editeur/integration.md, "Éditeur", 'Intégration']
  - [editeur/creation-template.md, "Éditeur", 'Création de template']
  - [editeur/exemple.md, "Éditeur", "Exemple"]
  - [exemples/php.md, "Exemples de code", "PHP"]
  - [infra/requirements.md, "Infrastructure", "Besoins matériels"]
  - [faq.md, FAQ]
  - [annexes.md, Annexes]
